function retrieveGender(){var a=(new URL(window.location.href)).searchParams.get("gender");a&&(1==a&&saveGender("male"),2==a&&saveGender("female"))}function saveGender(a){saveRegistrationStep({gender:a,step:0},"/MobRegStep1.html")}function saveLocation(a){saveRegistrationStep({cityId:a,step:1},"/MobRegStep2.html")}function saveRelationshipStatus(a){saveRegistrationStep({relationshipStatusId:a,step:2},"/MobRegStep3.html")}
function saveHeight(a){saveRegistrationStep({heightId:a,step:3},"/MobRegStep4.html")}function saveBodyShape(a){saveRegistrationStep({bodyShapeId:a,step:4},"/MobRegStep5.html")}function saveHairColor(a){saveRegistrationStep({hairColorId:a,step:5},"/MobRegStep6.html")}function saveEyeColor(a){saveRegistrationStep({eyeColorId:a,step:6},"/MobRegStep7.html")}
function saveDate(){var a=getBirthdayUser();null!=a&&validateOnBackend(a).then(function(b){b.valid?($("#birthdayError").addClass("hide"),$("#birthdayValueError").addClass("hide"),$("#birthdayYearError").hide(),saveRegistrationStep({birthday:a,step:7},"/MobRegStep8.html")):"notAllowedAge"===b.error?$("#birthdayError").removeClass("hide"):"toOld"===b.error&&$("#birthdayYearError").show()})}
function getBirthdayUser(){var a=$("#birthday").val(),b=$("#birthDay").val(),d=$("#birthMonth").val(),c=$("#birthYear").val();try{if(!(a||b&&d&&c))return $("#birthdayValueError").removeClass("hide"),null;if(a)var e=a.split("-"),a=e[2]+"-"+e[1]+"-"+e[0];else a=c+"-"+d+"-"+b;return validDate(a)?a:($("#birthdayValueError").removeClass("hide"),null)}catch(f){return $("#birthdayValueError").removeClass("hide"),null}}function validateOnBackend(a){return $.post("/api/v1/validation/age",{birthday:a})}
function validDate(a){a=a.split("-");var b=a[2];return(new Date(a[0],a[1],0)).getDate()>=b?!0:!1}function saveUsername(){var a=getUserName();null!=a&&saveRegistrationStep({username:a,step:8},"/MobRegStep9.html")}function getUserName(){var a=$("#username").val().trim();$(".warning-message").hide();return 3>a.length||20<a.length?($("#nicknameLengthError").show(),null):XRegExp("^([\\pL0-9_-]+(\\s[\\pL0-9_-]+)*){1,20}$","i").test(a)?encodeURIComponent(a):($("#nicknameFormatError").show(),null)}
function savePassword(){if(6>$("#newPassword").val().length)$("#passwordLengthError").show(),$("#regFinishButton").prop("disabled",!0);else if("false"==$("#step10").val())location.href="/MobHome.html";else{$("#step10").val("false");var a={newPassword:$("#newPassword").val(),gclid:$("#gclid").val()};showSpinner();$("#regFinishButton").prop("disabled",!0);$.post("/mobile/setPassword.action",a,function(a){void 0!=a.errors?($("#emailAlreadyExistsError").removeClass("hide"),$("#regFinishButton").prop("disabled",
!1),hideSpinner()):"false"==$("#howDoYouKnowAboutActive").val()?location.href="/MobHome.html":location.href="/MobRegStep11.html"})}}function saveHowDoYouKnowUs(){var a={hdUsValue:$("#firstLoginSelect").children("option:selected").val(),step:11};saveRegistrationStep(a,"/MobHome.html")}
function completeRegistration(a,b){if("false"==b.val())location.href="/MobHome.html";else if($("#confirmRegButton").prop("disabled",!0),99<$("#email").val().trim().length)$("#emailLengthError").show(),$("#confirmRegButton").prop("disabled",!1);else if(a&&6>$("#newPassword").val().length)$("#passwordLengthError").show(),$("#confirmRegButton").prop("disabled",!1);else{if($("#consentAgbCheckbox").length){if(!$("#consentAgbCheckbox").is(":checked"))return $("#confirmRegButton").prop("disabled",!1),$("#consentAndAgbError").show(),
!1}else{if(!$("#consentCheckbox").is(":checked")){$("#confirmRegButton").prop("disabled",!1);$("#consentError").show();return}if(!$("#agbAge").is(":checked")){$("#confirmRegButton").prop("disabled",!1);$("#agbError").show();return}}$("#consentError").hide();$("#agbError").hide();var d={email:encodeURIComponent($("#email").val().trim().toLowerCase()),sayHello:$("#sayHello").val(),isShortReg:a,newPassword:a?$("#newPassword").val():""};showSpinner();$.post("/mobile/completeRegistration.action",d,function(c){hideSpinner();
c.errors?-1!==c.errors.email.indexOf("emailAlreadyUsed")?($("#emailAlreadyExistsError").show(),$("#confirmRegButton").prop("disabled",!1)):-1!==c.errors.email.indexOf("emailDomainNotAllowed")?($("#emailDomainNotAllowedError").show(),$("#confirmRegButton").prop("disabled",!1)):-1!==c.errors.email.indexOf("thisEmailNotAllowed")?($("#emailNotAllowedError").show(),$("#confirmRegButton").prop("disabled",!1)):-1!==c.errors.email.indexOf("provider-email-not-valid")?(null!=c.data.didYouMean&&($("#didYouMeanLabel").removeClass("hide"),
$("#didYouMean").text(c.data.didYouMean+"?")),$("#providerEmailNotValid").show(),$("#confirmRegButton").prop("disabled",!1)):-1!==c.errors.email.indexOf("provider-email-disposable")?($("#emailDisposableValidError").show(),$("#confirmRegButton").prop("disabled",!1)):($("#confirmRegButton").prop("disabled",!1),b.val("false")):($("#emailAlreadyExistsError").hide(),$("#emailDomainNotAllowedError").hide(),location.href=a?"/MobHome.html":"/MobRegStep10.html")}).fail(function(a){console.error("Internal server error");
$("#confirmRegButton").prop("disabled",!1);hideSpinner()})}}function saveRegistrationStep(a,b){showSpinner();$.post("/mobile/saveRegistrationStep.action",a,function(a){a&&a.errors?hideSpinner():location.href=b})}function showSpinner(){$(".spinner").show();$(".container").hide()}function hideSpinner(){$(".spinner").hide();$(".container").show()}function toggleFloatingHeader(){40<$(window).scrollTop()?$("body").addClass("scroll"):$("body").removeClass("scroll")}
function saveDateAndNicknameShortReg(){var a=getUserName(),b=getAge();null!=a&&null!=b&&saveRegistrationStep({age:b,username:a,isShortReg:!0,step:2},"/MobRegStep3.html")}function getAge(){var a=$("#birthAge").val();return a?a:($("#ageValueError").removeClass("hide"),null)}window.addEventListener("pageshow",function(a){hideSpinner()},!1);
$(function(){retrieveGender();$(".mobile-date").change(function(){valdate=$(this).val();console.log(valdate);valdate?$(".placeholder").hide():$(".placeholder").show()});$.validator.methods.email=function(a,b){return this.optional(b)||XRegExp("^[\\pL0-9._%+-]+@(?!thecasuallounge)[\\pL0-9.-]+\\.(com|net|org|edu|int|mil|gov|arpa|biz|aero|name|coop|info|pro|museum|en|ru|ua|pl|de|fr|at|ch|no|se|sk|cz|it|uk|dk)$","i").test(a)};$(window).on("scroll",toggleFloatingHeader);$(document.body).on("touchmove",
toggleFloatingHeader);$("#locationSearch").on("keyup",function(){$.get("/api/v1/geolocation/locations?limit\x3d25\x26locationName\x3d"+$("#locationSearch").val(),{},function(a){0!=$("#locationSearch").val().length&&showSpinner();$(".geo-location-list").html("");a.forEach(function(a){$(".geo-location-list").append('                    \x3cli\x3e                        \x3ca href\x3d"#" onclick\x3d"saveLocation('+a.cityId+')" class\x3d"btn btn-white btn-block"\x3e'+a.cityName+"\x3c/a\x3e                    \x3c/li\x3e                ")});
hideSpinner()})});$("#firstLoginSelect").change(function(){$("#firstLoginButton").removeAttr("disabled")});$("#username").on("keydown",function(){$("#nicknameError").addClass("hide")});$("#birthday").on({change:function(){$("#birthdayValueError").addClass("hide");-1<navigator.userAgent.toLowerCase().indexOf("android")&&saveDate()},blur:function(){navigator.platform&&/iPad|iPhone|iPod/.test(navigator.platform)&&saveDate()}});$("#email").on("input",function(){$("#emailAlreadyExistsError").hide();$("#emailDomainNotAllowedError").hide()});
$("#newPassword").on("input",function(){var a=$(this).val();!a||6>a.length?($("#passwordLengthError").show(),$("#regFinishButton").prop("disabled",!0)):($("#passwordLengthError").hide(),$("#regFinishButton").prop("disabled",!1))});$("#formRegistrationEmail").validate({rules:{email:{required:!0,email:!0}},errorContainer:"#emailNotValidError",errorPlacement:function(){return!0},submitHandler:function(){completeRegistration(!1,$("#step9"));return!1}});$("#formRegistrationShortReg").validate({rules:{email:{required:!0,
email:!0},newPassword:{required:!0}},errorContainer:"#emailNotValidError",errorPlacement:function(){return!0},submitHandler:function(){completeRegistration(!0,$("#step3"));return!1}});$("html, body").animate({scrollTop:$(".btn.active").offset().top-150},500);document.body.addEventListener("touchstart",function(a){$(".btn.active").removeClass("active")},!1);$(".mobile-suggestions-field").focus(function(){$("body").addClass("mobile-field-top-view")});$(".mobile-suggestions-field").focusout(function(){$("body").removeClass("mobile-field-top-view")})});